---
# Jangan di ubah
rule-providers:
  browsing:
    type: http
    behavior: classical
    path: "./browsing.yaml"
    url: https://raw.githubusercontent.com/Lynn-noob-afk/CFA/main/browsing.yaml
  umum:
    type: http
    behavior: classical
    path: "./umum.yaml"
    url: https://raw.githubusercontent.com/Lynn-noob-afk/CFA/main/umum.yaml
  streaming:
    type: http
    behavior: classical
    path: "./streaming.yaml"
    url: https://raw.githubusercontent.com/Lynn-noob-afk/CFA/main/streaming.yaml
  portgame:
    type: http
    behavior: classical
    path: "./portgames.yaml"
    url: https://raw.githubusercontent.com/Lynn-noob-afk/CFA/main/portgames.yaml
  game:
    type: http
    behavior: classical
    path: "./gaming.yaml"
    url: https://raw.githubusercontent.com/Lynn-noob-afk/CFA/main/gaming.yaml
  sosmed:
    type: http
    behavior: classical
    path: "./sosmed.yaml"
    url: https://raw.githubusercontent.com/Lynn-noob-afk/CFA/main/sosmed.yaml
  telegramcidr:
    type: http
    behavior: ipcidr
    path: "./telegramcidr.yaml"
    url: https://raw.githubusercontent.com/Lynn-noob-afk/CFA/main/telegramcidr.yaml
  games:
    type: http
    behavior: domain
    path: "./games.yaml"
    url: https://raw.githubusercontent.com/Lynn-noob-afk/CFA/main/games.yaml
  domain1:
    type: http
    behavior: domain
    path: "./domain1.yaml"
    url: https://raw.githubusercontent.com/Lynn-noob-afk/CFA/main/domain1.yaml
  domain2:
    type: http
    behavior: domain
    path: "./domain2.yaml"
    url: https://raw.githubusercontent.com/Lynn-noob-afk/CFA/main/domain2.yaml
proxy-providers:
  VPN:
    type: file
    path: "./akun.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 300
proxy-groups:
 - name: Internet
   type: fallback
   disable-udp: false
   use:
   - VPN
   url: http://www.gstatic.com/generate_204
   interval: '30'
 - name: Browsing
   type: select
   disable-udp: false
   proxies:
   - DIRECT
   - REJECT
   use:
   - VPN
   url: http://www.gstatic.com/generate_204
   interval: '300'
 - name: Gaming
   type: url-test
   disable-udp: false
   proxies:
   - DIRECT
   - REJECT
   use:
   - VPN
   url: http://www.gstatic.com/generate_204
   interval: '600'
 - name: Sosmed & Chatting
   type: select
   disable-udp: false
   proxies:
   - DIRECT
   - REJECT
   use:
   - VPN
   url: http://www.gstatic.com/generate_204
   interval: '300'
 - name: Streaming
   type: select
   disable-udp: false
   proxies:
   - DIRECT
   - REJECT
   use:
   - VPN
   url: http://www.gstatic.com/generate_204
   interval: '300'
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ''
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  default-nameserver:
  - 8.8.8.8 #google
  - 8.8.4.4 #google
  - 1.1.1.1 #cloudflare
  - 1.0.0.1 #cloudflare
  - 9.9.9.9 #quaddns
  - 9.9.9.11 #quaddns
  - 192.168.170.28 #Tsel
  - 192.168.178.28 #Tsel
  - 192.168.130.28 #Tsel
  - 112.215.220.254 #Axis
  - 112.215.219.254 #Axis
  - 140.213.82.253 #Axis
  - 140.213.82.254 #Axis
  - 112.215.203.248 #Axis
  - 112.215.203.254 #Axis
  - 112.215.37.182 #XL
  - 112.215.37.183 #XL
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
  nameserver:
  - 8.8.8.8 #google
  - 8.8.4.4 #google
  - 1.1.1.1 #cloudflare
  - 1.0.0.1 #cloudflare
  - 9.9.9.9 #quaddns
  - 9.9.9.11 #quaddns
  - 192.168.170.28 #Tsel
  - 192.168.178.28 #Tsel
  - 192.168.130.28 #Tsel
  - 112.215.220.254 #Axis
  - 112.215.219.254 #Axis
  - 140.213.82.253 #Axis
  - 140.213.82.254 #Axis
  - 112.215.203.248 #Axis
  - 112.215.203.254 #Axis
  - 112.215.37.182 #XL
  - 112.215.37.183 #XL
  fallback:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.9
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,browsing,Browsing
- RULE-SET,umum,Browsing
- RULE-SET,game,Gaming
- RULE-SET,games,Gaming
- RULE-SET,portgame,Gaming
- RULE-SET,domain1,Sosmed & Chatting
- RULE-SET,sosmed,Sosmed & Chatting
- RULE-SET,telegramcidr,Sosmed & Chatting
- RULE-SET,domain2,Streaming
- RULE-SET,streaming,Streaming
- MATCH,GLOBAL
- GEOIP,ID,Gaming
- GEOIP,ID,Browsing
